name: TG-parser

on:
  workflow_dispatch: # Ручной запуск из интерфейса GitHub
  schedule:
    - cron: '0 */6 * * *' # Запускать ежедневно каждые 6 часов

jobs:
  run-tg-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Используем Python 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 asyncio

      - name: Run tg-parser.py
        run: python tg-parser.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add telegram_channels.json config-tg.txt channel_failure_history.json # Добавлен channel_failure_history.json
          git commit -m "Автоматическое обновление telegram_channels.json, config-tg.txt и channel_failure_history.json" || echo "No changes to commit" # Обновлено сообщение коммита
          git push origin main || echo "No changes to push"
