name: TG-parser

on:
  workflow_dispatch: # Ручной запуск из интерфейса GitHub
  schedule:
    - cron: '0 */6 * * *' # Запускать ежедневно каждые 6 часов

jobs:
  run-tg-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        id: install-deps-cache # Уникальный ID для шага кэширования
        uses: actions/cache@v3
        with:
          path: ~/.pip/cache # Путь к кэшу pip
          key: pip-cache-${{ runner.os }}-${{ python-version }}-direct-deps-${{ hashString('requests beautifulsoup4 geoip2') }} # Ключ кэша, основанный на списке зависимостей
          restore-keys: |
            pip-cache-${{ runner.os }}-${{ python-version }}-direct-deps- # Ключ для восстановления кэша (если точный ключ не найден)
      - name: Install dependencies (если кэш не найден)
        if: steps.install-deps-cache.outputs.cache-hit != 'true' # Выполнять только если кэш не был использован
        run: |
         python -m pip install --upgrade pip
         pip install requests beautifulsoup4 geoip2

      - name: Run tg-parser.py
        run: python tg-parser.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add telegram_channels.json config-tg.txt channel_failure_history.json # Добавлен channel_failure_history.json
          git commit -m "Автоматическое обновление telegram_channels.json, config-tg.txt и channel_failure_history.json" || echo "No changes to commit" # Обновлено сообщение коммита
          git push origin main || echo "No changes to push"
